### ISSUE TITLE
Submit RFC for Configuration-Context header

### ISSUE THREAD

**Issue by ndjc** [oslc-op/oslc-specs#425] opened 2020-08-28 18:41 UTC
After the draft RFC has been reviewed internally (issue #206), and after the PSD01 is published, we need to submit the RFC to IETF.

**Comment by ndjc** [comment] 2020-08-28 18:43
See also issue #144.

**Comment by berezovskyi** [comment] 2021-02-06 17:36
duplicate of #144 (feel free to reopen if you prefer to keep 3 issues)

**Closed by berezovskyi** 2021-02-06 17:36 UTC
Labels: Domain: CfgM
